### ISSUE TITLE
Request for cooling mode

### ISSUE THREAD

**Issue by DrTomek** [soundvibe/ha-danfoss#12]
Hi.
First of all I want to thank you for excellnet job with this addon. It works just like it should and consumes much less resources than openHab container running parallel with my HA.
I am using Danfoss Icon with additional module which can switch Danfoss controller between heating and cooling. I have noticed that your addon provide only mode off and heating. Official Danfoss App can display if there is cooling or heating running on each thermostat.
Would it be possible to add cooling mode to thermostats in your addon? It would help me with automations a lot.

Best regards :)

**Comment by soundvibe** [comment]
Hey,

I see that there is `cooling enabled` message code in API which should indicate when cooling is enabled. Since I don't have cooling integrated in my heating system, I am not sure how this works and I can't test it. As for heating, there is simple boolean flag in API which tells if heating is `OFF` or `ON`, I would guess that this should probably work in combination with `cooling enabled` flag, e.g. `if cooling enabled and heating state is ON`, then it means it is in Cooling state. Would it make sense, WDYT?

**Comment by DrTomek** [comment]
Hi. 
I just have updated the addon and mode cooling is available in thermostat modes and it shows state correctly.

Thank You :)
